### ISSUE TITLE
Add verified proofs to schema

### ISSUE THREAD

**Issue by VGLoic** [semaphore-protocol/subgraph#1]
**Is your feature request related to a problem? Please describe.**

It is currently not possible to retrieve the on chain verified proofs using the subgraph

**Describe the solution you'd like**

We could add the `VerifiedProof` entity to the schema as
```
type VerifiedProof @entity {
    id: ID!
    signal: Bytes!
    group: Group!
}
```

Additionally, the Group entity could be updated as follows
```
type Group @entity {
    id: ID!
    depth: Int!
    zeroValue: BigInt!
    root: BigInt!
    size: Int!
    numberOfLeaves: Int!
    admin: Bytes!
    members: [Member!]! @derivedFrom(field: "group")
    verifiedProofsCount: Int!
    verifiedProofs: [VerifiedProof!]! @derivedFrom(field: "group")
}
```

I added the `verifiedProofsCount` as a way to keep track of the number of published verified proofs and use it in order to generate the ID of new proof as `ID = hash(verifiedProofsCount, group ID)`

Happy to hear opinions on this :)

**Describe alternatives you've considered**

For now, I retrieve the past events for `ProofVerified` using usual Ethereum provider

**Additional context**

I did a version of this on a branch of a fork [here](https://github.com/VGLoic/subgraph/tree/feat/verified-proofs). Happy to convert it to a PR if the feature ended being interesting :)

The deployed version can be found on my [hosted service](https://thegraph.com/hosted-service/subgraph/vgloic/semaphore-fork?selected=playground)

**Comment by cedoor** [comment]
Hey @VGLoic , thank you very much for this issue, I think it's very important. Would it be possible to add only 1 `signals` field to the Group entity as an array of Bytes? If we can avoid adding a new entity just for signals I think it's better. How does it sound?

**Comment by VGLoic** [comment]
Yes totally!

The only downside I would see to not have it as an entity would be to not have the pagination (and filter) options when resolving the `signals` inside a `group`, i.e. we will not be able to do
```
{
  groups {
    id
    verifiedProofs(first: 10) {
      signal
    }
  }
}
```
Would you see it as an issue? :)

**Comment by cedoor** [comment]
You're right, that could be a problem. Let's keep it as an entity then :) I would also add the signal to the id hash:

`ID = hash(numberOfSignals, group ID, signal)`

Isn't it possible to get the number of signals from the `group.signals` array? Something like `group.signals.length`?

**Comment by VGLoic** [comment]
>  I would also add the signal to the id hash

Sure!

> Isn't it possible to get the number of signals from the group.signals array? Something like group.signals.length?

To be honest, I tried that way at first but it was not able to get the `signals` (and then the length) 🙈 I am gonna give it a new try with some look at the docs, it would indeed be cleaner to not have this field

Do you have a preference between `Signal` or `VerifiedProof` in terms of naming for the entity?

I did go for `VerifiedProof` in order to let the `signal` name for a field of the `VerifiedProof` but I don't mind going for `Signal` and use `value` (or else) for the field carrying the actual signal value

**Comment by cedoor** [comment]
> To be honest, I tried that way at first but it was not able to get the `signals` (and then the length) see_no_evil I am gonna give it a new try with some look at the docs, it would indeed be cleaner to not have this field

Great, thank you!

> Do you have a preference between `Signal` or `VerifiedProof` in terms of naming for the entity?

I think `VerifiedProof` is ok, it's more generic and we might add other proof fields later.

**Comment by VGLoic** [comment]
Hey 👋 

#### Regarding the replacement of `verifiedProofsCount` with `group.verifiedProofs.length`

I was not able to retrieve the `verifiedProofs` field at the handler level. As I understood it's not possible to do it because the `@derivedFrom` fields are only virtual fields and hence not accessible at the handlers level. 

An other way that would work is to not derive this field and registering the verified proof in the array of the group, however, it is not the advised way from the [docs](https://thegraph.com/docs/en/developing/creating-a-subgraph/#reverse-lookups) as some performance are lost in the way :/

#### Others

I also added the fields `timestamp` (block timestamp) and `index` (length of the array at insertion time) in order to allow the ordering of the signals by chronological order

I made a [PR](https://github.com/semaphore-protocol/subgraph/pull/2) for these changes

Happy to hear your thoughts!

**Comment by cedoor** [comment]
Hi @VGLoic, great job! Thank you very much 😃
